#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 31 15:05:27 2017

@author: kburdge
"""

import os, sys
import time
import optparse
import pandas as pd
import numpy as np
import h5py
import glob
import json

import matplotlib
matplotlib.use('Agg')
matplotlib.rcParams.update({'font.size': 12})
matplotlib.rcParams['contour.negative_linestyle'] = 'solid'
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.colors import LogNorm

from astropy.io import fits

def parse_commandline():
    """
    Parse the options given on the command-line.
    """
    parser = optparse.OptionParser()

    parser.add_option("--infile",default="/Users/mcoughlin/Downloads/lcogtdata-20190913-6/nttZTFJ1942-1032_fts_20190912_merge_1.6_58739_1_2df_ex.fits")
    parser.add_option("-o","--outputDir",default="../output")

    opts, args = parser.parse_args()

    return opts

# Parse command line
opts = parse_commandline()
infile = opts.infile
outputDir = opts.outputDir

if not os.path.isdir(outputDir):
    os.makedirs(outputDir)

hudl = fits.open(infile)
data = hudl[0].data
header = hudl[0].header

flux = data[0][0]
optflux = data[1][0]
sky = data[2][0]
fluxerr = data[3][0]

xmin = header["XMIN"]
xmax = header["XMAX"]
wavelengths = np.linspace(xmin,xmax,len(flux))

outputFile = os.path.join(outputDir,'spectrum.pdf')
plt.figure(figsize=(10,6))
plt.errorbar(wavelengths, flux, yerr=fluxerr,fmt='k',label='Object')
plt.plot(wavelengths, sky,'b--',label='Sky')
plt.xlabel('Wavelength [A]')
plt.ylabel('Flux [erg/cm2/s/A  10^20]')
plt.legend()
plt.savefig(outputFile)
plt.close()

outputFile = os.path.join(outputDir,'spectrum.json')
fluxdat = []
for wave, fl, flerr in zip(wavelengths, flux, fluxerr):
    fluxdat.append({"wavelength": str(wave),
                    "flux": str(fl),
                    "fluxerr": str(flerr)})

data = {"telescope": "%s" % header['TELESCOP'],
        "instrument": "LCO",
        "filter": header['FILTER1'],
        "mjd": str(header['MJD-OBS'] + header['EXPTIME']/2.0),
        "wavelength_unit": "A",
        "flux_unit": "erg/cm2/s/A  10^20",
        "data": fluxdat 
}

with open(outputFile, 'w') as f:
    json.dump(data, f)

