#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 31 15:05:27 2017

@author: kburdge
"""

import os, sys
import time
import optparse
import pandas as pd
import numpy as np
import h5py
import glob

import matplotlib
matplotlib.use('Agg')
matplotlib.rcParams.update({'font.size': 16})
matplotlib.rcParams['contour.negative_linestyle'] = 'solid'
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.colors import LogNorm

from astropy.io import fits

def parse_commandline():
    """
    Parse the options given on the command-line.
    """
    parser = optparse.OptionParser()

    parser.add_option("--infile",default="/Users/mcoughlin/Downloads/lcogtdata-20190913-6/nttZTFJ1942-1032_fts_20190912_merge_1.6_58739_1_2df_ex.fits")
    parser.add_option("-o","--outputDir",default="../output")

    opts, args = parser.parse_args()

    return opts

# Parse command line
opts = parse_commandline()
infile = opts.infile
outputDir = opts.outputDir

hudl = fits.open(infile)
data = hudl[0].data
header = hudl[0].header

flux = data[0][0]
optflux = data[1][0]
sky = data[2][0]
fluxerr = data[3][0]

xmin = header["XMIN"]
xmax = header["XMAX"]
wavelengths = np.linspace(xmin,xmax,len(flux))

outputFile = os.path.join(outputDir,'spectrum.pdf')
plt.figure()
plt.plot(wavelengths, flux,'k--')
plt.plot(wavelengths, sky,'b--')
plt.savefig(outputFile)
plt.close()

